넘파이 모듈

In [1]:
# 모듈 임포트
import numpy as np

실습

In [3]:
#np.array() 함수
#ndarray.shape: ndarray의 차원과 크기를 튜플() 형태로

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array4 array 형태:',array3.shape)


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array4 array 형태: (1, 3)


In [4]:
# ndarray.ndim: ndarray의 차원
print('array1:{:0}차원, array2:{:1}차원,array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원,array3: 2차원


In [9]:
# ndarray의 데이터 타입

list1 = [1,2,3]
print(type(list1))
array1= np.array(list1)  #리스트 자료형인list1을 ndarray로 변경
print(type(array1))
print(array1,array1.dtype)

list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [8]:
# astype(): ndarray내 데이터타입 변경

array_int=np.array([1,2,3])
array_float= array_int.astype('float64') # .astype()
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [13]:
# arrange(), zeros(), ones() 이용해 ndarray 생성

# arrange() : array를 range()로 표현.0부터 함수인자값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

# zero() : ndarray.shape시에 모든 값을 0(int)으로 채워 ndarray반환
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# one() : ndarray.shape시에 모든 값을 1(float64형)로 채워 ndarray반환
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [18]:
# reshape()
# :ndarray를 특정차원 및 크기로 변환. 원하는 크기를 인자로 부여
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

# reshape 효율적 사용 -> reshape()의 인자를 -1로 적용하는 경우
array1 = np.arange(10)
print('array1:\n',array1)
array2 = array1.reshape(-1,5)
print('array2:\n', array2.shape)
array3 = array1.reshape(5,-1)
print('array3:\n', array3.shape)
#ndarray와 호환되는 shape로 스스로 변환

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 (2, 5)
array3:
 (5, 2)


In [20]:
# 인덱싱(indexing)
# 넘파이에서 ndarray내 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 함

# 1.단일 특정값 추출

# 2.슬라이싱

# 3.팬시 인덱싱
# 리스트나 ndarray로 인덱스 집합 지정하면 해당 위치의 인덱스에 해당하는 ndarray반환하는 방식

# 4.불린 인덱싱
# 조건 필터링과 검색이 동시에 가능한 방식
array1d = np.arange(start=1,stop=10)
array3 = array1d[array1d>5]  # [ ]안에 array1d>5 , Boolean indexing을 적용
print('array1d > 5 불린인덱싱 결과 값:', array3)
#필터링과정
array1d >5

array1d > 5 불린인덱싱 결과 값: [6 7 8 9]


array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
# 행렬의 정렬

# sort(): 두가지 행렬 정렬방식 존재

org_array = np.array([3,1,9,5])
print('원본행렬:',org_array)
# 1.np.sort() : 원 행렬은 그대로 유지한채 원 행렬의 정렬된 행렬을 반환
sort_array1 = np.sort(org_array)
print('np.sort()호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort()호출 후 원본 행렬:', org_array)

# 2.ndarray.sort() : 원 행렬자체를 정렬한 형태로 변환하며 반환 값은 None

# argsort():정렬된 행렬의 인덱스를 반환하기